# Generated by Django 4.2.23 on 2025-06-25 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_categoria', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_editorial', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_multa', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoginUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('copias_totales', models.PositiveIntegerField(default=1)),
                ('copias_disponibles', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_devolucion', models.DateField(blank=True, null=True)),
                ('cantidad_renovaciones', models.PositiveIntegerField(default=0)),
                ('login_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.loginusuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('monto_multa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_generacion_multa', models.DateField(auto_now_add=True)),
                ('fecha_pago_multa', models.DateField(blank=True, null=True)),
                ('estado_multa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.estadomulta')),
                ('prestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.prestamo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_publicacion', models.CharField(blank=True, max_length=4, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionApp.categoria')),
                ('editorial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GestionApp.editorial')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.stock')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.libro')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionApp.prestamo')),
            ],
        ),
    ]
