# Generated by Django 4.2.23 on 2025-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('basica', 'Estudiante (Básica/Media)'), ('universitario', 'Universitario'), ('adulto', 'Adulto')], default='adulto', max_length=50),
        ),
    ]
